import type { AminoAcid } from "./types"

export const AMINO_ACIDS = [
  "A",
  "R",
  "N",
  "D",
  "C",
  "E",
  "Q",
  "G",
  "H",
  "I",
  "L",
  "K",
  "M",
  "F",
  "P",
  "S",
  "T",
  "W",
  "Y",
  "V",
  "-",
] as const

export const COLORS = {
  cysteine: "#FFEA00",
  glycine: "#C4C4C4",
  negativelyCharged: "#FC9CAC",
  positivelyCharged: "#BB99FF",
  polarUncharged: "#80BFFF",
  hydrophobic: "#67E4A6",
  gap: "transparent",
} as const

export const AMINO_ACID_COLORS: Record<AminoAcid, string> = {
  C: COLORS.cysteine,
  G: COLORS.glycine,
  D: COLORS.negativelyCharged,
  E: COLORS.negativelyCharged,
  K: COLORS.positivelyCharged,
  R: COLORS.positivelyCharged,
  S: COLORS.polarUncharged,
  T: COLORS.polarUncharged,
  H: COLORS.polarUncharged,
  Q: COLORS.polarUncharged,
  N: COLORS.polarUncharged,
  A: COLORS.hydrophobic,
  I: COLORS.hydrophobic,
  L: COLORS.hydrophobic,
  M: COLORS.hydrophobic,
  F: COLORS.hydrophobic,
  W: COLORS.hydrophobic,
  Y: COLORS.hydrophobic,
  V: COLORS.hydrophobic,
  P: COLORS.hydrophobic,
  "-": COLORS.gap,
}